name: allen2tract
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - allensdk
  - jupyter
  - nipype
  - libpng
  - libblas
  - liblapack
  - gfortran
  - pillow
  - webcolors
  - plotly
  - matplotlib
  - scikit-image
  - pycodestyle
  - dipy
  - fury